[{"strategy": "retry", "code": "\npackage org.apache.commons.collections4;\n\nimport org.junit.jupiter.api.Test;\nimport java.util.Enumeration;\nimport java.util.Vector;\n\nimport static org.junit.jupiter.api.Assertions.*;\n\npublic class EnumerationUtils_getTest {\n\n    @Test\n    public void testGet_ValidIndex() {\n        Vector<String> vector = new Vector<>();\n        vector.add(\"A\");\n        vector.add(\"B\");\n        vector.add(\"C\");\n        Enumeration<String> enumeration = vector.elements();\n\n        String result = EnumerationUtils.get(enumeration, 1);\n        assertEquals(\"B\", result);\n    }\n\n    @Test\n    public void testGet_InvalidIndex() {\n        Vector<String> vector = new Vector<>();\n        vector.add(\"A\");\n        Enumeration<String> enumeration = vector.elements();\n\n        IndexOutOfBoundsException exception = assertThrows(IndexOutOfBoundsException.class, () -> {\n            EnumerationUtils.get(enumeration, 1);\n        });\n        assertEquals(\"Entry does not exist: 1\", exception.getMessage());\n    }\n}\n"}]